#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 高校化学ChemQuiz                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 無料                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : いつでも、手軽に化学の学習。

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 高校化学ChemQuiz制作チーム                               
your_link                                 : https://thomas1102-hiro.github.io/chemquiz/                     
your_city                                 : Tokyo                               
email_address                             : contact@yhiro.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : Thomas1102-hiro
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : ちょっとした空き時間に手軽に、無料で学習。
    description                           : iPhone,iPad対応アプリ（Android版のリリースは現在未定）。直感で答えられるようなスタイルですので、バスの待ち時間や寝る前などはもちろん、一定時間を決めて集中して学習することもできます。あなたの学習スタイルに合わせて、チャレンジしてみましょう。
    fontawesome_icon_name                 : magic
    
  - title                                 : 高校化学の各単元別にクイズを用意。
    description                           : 高校化学の基礎である「粒子の結合・結晶構造」はもちろん、受験前の限られた期間で知識習得が必要とされる「芳香族炭化水素」まで、幅広い単元を用意（一部制作製作中の単元は除く）。苦手な単元を集中して学習したり、テスト範囲を全体的に復習するなど、自分にあった使い方ができます。
    fontawesome_icon_name                 : mobile

  - title                                 : ５種類のクイズで、いろんな角度から知識が身につく
    description                           : いわゆる○×クイズのような正誤問題から、組み合わせ問題、一択問題、マルチ選択問題、空欄補充問題を用意。学習したばかりの単元は正誤問題を重点的に学習したり、力をつけたい単元は５種類全てチャレンジしてみるのもいいかもしれません。
    fontawesome_icon_name                 : play-circle

  - title                                 : 出題はランダム形式。基礎問題も応用問題もまんべんなく。
    description                           : 学習したい単元とクイズの種類を選択すると、１回あたりランダムに合計１０問のクイズが出題されます。間違えた場合は正解するまで再度出題されるので、より記憶に残るでしょう。解説もついているので、わからない場合は解説を見て再回答できます。解説がわかりにくかったり、詳しい解説のリクエストも受け付けています。
    fontawesome_icon_name                 : sync

  - title                                 : 全国ランキングで、全国の化学学習ユーザと切磋琢磨しよう。
    description                           : ただクイズを解くのもいいですが、スコアのウィークリーランキングシステムも搭載していますので、日々の学習へのモチベーションになるかもしれません。トップランクを獲得したり、一定の好成績を残したユーザにはちょっとしたお楽しみや特典を用意。
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown